#!/bin/csh

#
# Install
#
# Installs product "allcacheload" in the appropriate directory
#
# 1. cvs export -r allcacheload-#-#-# allcacheload
# 2. Copy Configuration.default Configuration
# 3. Edit Configuration
# 4. Install
#

cd `dirname $0` && source ./Configuration

if ( ! -d ${ALLCACHEDIR} ) then
	mkdir -p ${ALLCACHEDIR}
endif

if ( ! -d ${ALLCACHEINDIR} ) then
	mkdir -p ${ALLCACHEINDIR}
endif

if ( ! -d ${ALLCACHEBCPDIR} ) then
	mkdir -p ${ALLCACHEBCPDIR}
endif

if ( ! -d ${ALLCACHELOGDIR} ) then
	mkdir -p ${ALLCACHELOGDIR}
endif

ln -s allelecombination.py allelecombinationByAllele.py
ln -s allelecombination.py allelecombinationByMarker.py
ln -s allelecombination.py allelecombinationByGenotype.py

